### ISSUE TITLE
Control flow limitation

### ISSUE THREAD

**Issue by DeadParrot** [snoack/python-goto#10]
This is probably tricky to fix but if the goto adds the ability for control to flow into code that it otherwise couldn't the bytecode patching doesn't work. Here's a little example:
```python
from goto import with_goto

@with_goto
def foo():
    goto .skip
    return # Causes SyntaxError: Unknown label 'skip'
    label .skip
    print('skip')

foo()
```
If the `return` is removed it works fine.

**Comment by snoack** [comment]
IIRC, this depends on the Python version, where newer versions of CPython don't generate bytecode for dead code after unconditional return. I don't think there is anything that can be done about that.

**Comment by DeadParrot** [comment]
That makes sense. I get a different error (unknown opcode) in Python 2.7 so I guess it is also doing similar bytecode pruning.

Fixing this would require pre-scanning the source and changing the logic to avoid apparent dead code that goto can cause to be undead. Since this would be slow at run time it would be best as a code static analysis tool I think. Probably not worth the effort.

**Comment by snoack** [comment]
It would not only be slow, but the original source code isn't always available at runtime.

The error you see in Python 2.7 seems unexpected though. There might be a bug.
