### ISSUE TITLE
Question - how to to use goto with a string

### ISSUE THREAD

**Issue by eoglethorpe** [snoack/python-goto#11]
Not sure the best way to phrase this but here we go. Let's say depending on a method input I want to go to given parts of my code. A kludgy way would be:

```
def go( destination ):
  if destination == 'one':
    goto.one
  elif destination == 'two':
    goto.two
  
  label.one
  pass
 
  label.two
  pass
```

Now in reality let's say that I want to go to whatever label is specified by the method parameter, I would have something like this:

```
def go( destination ):
  goto.destination
```

This doesn't work and neither does `getattr(goto, destination)`.

Any thoughts? Cheers.

**Comment by snoack** [comment]
Since the way this works, is by statically rewriting the bytecode, it's not possible to have evaluated `goto` targets. However, it is possible to dynamically generate the code:

```python
def go(destination):
    exec(with_goto(compile('''
goto .{}

label .one
pass

label .two
pass'''.format(destination), '', 'exec')))
```
