### ISSUE TITLE
Does this work with Pyhon 3

### ISSUE THREAD

**Issue by wolfamongus2** [snoack/python-goto#13]
```python
from goto import with_goto

@with_goto
def range(start, stop):
    i = start
    result = []

    label .begin
    if i == stop:
        goto .end

    result.append(i)
    i += 1
    goto .begin

    label .end
    return result

print(range(0, 10))
```

Gives me a whole bunch of errors.

**Comment by snoack** [comment]
Which Python version? Please post the whole traceback.

**Comment by Kijewski** [comment]
Also fix your the markup, please. Whitespaces are kinda important in Python. Either prefix your code with four spaces / one tab in every line, or wrap in it

````markdown
```python
YOUR CODE HERE
```
````

**Comment by zhangysh1995** [comment]
Doesn't work with my python3.5 version either: ``unresolved reference label``

**Comment by snoack** [comment]
What doesn't work? If I run the above code with Python 3.5.3, I get the expected output without any errors.

**Comment by snoack** [comment]
So you say, you get a linter warning in PyCharm, but the code runs as expected?

This is to be expected as linters only look at the source code, and not at the effective bytecode, and without the changes done to the bytecode by the `with_goto` decorator, you would get the exception, PyCharm is warning you about.
