### ISSUE TITLE
async def error

### ISSUE THREAD

**Issue by yxlwfds** [snoack/python-goto#27]
@with_goto
    async def asr(self, data, token=None):
        label .begin
        ac = await self.checkapp(account)

python3.8.1

**Comment by yxlwfds** [comment]
`File "./data.py", line 45, in Acc
    async def asr(self, data, token=None):
  File "/root/.local/share/virtualenvs/aass-CfyZseTz/lib/python3.8/site-packages/goto.py", line 184, in with_goto
    _patch_code(func_or_code.__code__),
  File "/root/.local/share/virtualenvs/aass-CfyZseTz/lib/python3.8/site-packages/goto.py", line 175, in _patch_code
    return _make_code(code, buf.tostring())
  File "/root/.local/share/virtualenvs/aass-CfyZseTz/lib/python3.8/site-packages/goto.py", line 53, in _make_code
    return types.CodeType(*args)
TypeError: an integer is required (got type bytes)`

**Comment by insignification** [comment]
I have a fork & PR with python 3.8 support.
I also have a fork with async support too (it works in python 3.8, though not in all other versions [yet?], so no PR): https://github.com/insignification/python-goto/tree/async

**Comment by yxlwfds** [comment]
> I have a fork & PR with python 3.8 support.
> I also have a fork with async support too (it works in python 3.8, though not in all other versions [yet?], so no PR): https://github.com/insignification/python-goto/tree/async

thanks
