### ISSUE TITLE
goto is reserved on PyPI

### ISSUE THREAD

**Issue by graingert** [snoack/python-goto#3]
You should pick a different name in your setup.py

**Comment by wesclemens** [comment]
Shouldn't this be a bug on the PyPI project?

**Comment by graingert** [comment]
@wesclemens This is the project that uploads to PyPI

**Comment by wesclemens** [comment]
@graingert Aww I see what you mean. I thought you meant that you couldn't have a name of goto you mean it's already taken.

**Comment by snoack** [comment]
I [renamed](https://github.com/snoack/python-goto/commit/c1c6fe72518769891d320de21fec79e4b09e84b1#diff-2eeaed663bd0d25b7e608891384b7298R4) it to `goto-statement` (the module name remains `goto` though) and uploaded it to [PyPi](https://pypi.python.org/pypi/goto-statement).
